export const appLanguages = [
  { key: "ar", title: "Arabic", titleTranslate: "العربية" },
  { key: "am", title: "Amharic", titleTranslate: "አማርኛ" },
  { key: "bg", title: "Bulgarian", titleTranslate: "български" },
  { key: "bn", title: "Bengali", titleTranslate: "বাংলা" },
  { key: "ca", title: "Catalan", titleTranslate: "Català" },
  { key: "cs", title: "Czech", titleTranslate: "Čeština" },
  { key: "da", title: "Danish", titleTranslate: "Dansk" },
  { key: "de", title: "German", titleTranslate: "Deutsch" },
  { key: "el", title: "Greek", titleTranslate: "Ελληνικά" },
  { key: "en", title: "English", titleTranslate: "English" },
  {
    key: "en-AU",
    title: "English (Australia)",
    titleTranslate: "English (Australia)",
  },
  {
    key: "en-GB",
    title: "English (Great Britain)",
    titleTranslate: "English (Great Britain)",
  },
  { key: "en-US", title: "English (USA)", titleTranslate: "English (USA)" },
  { key: "es", title: "Spanish", titleTranslate: "Español" },
  {
    key: "es-419",
    title: "Spanish (Latin America and Caribbean)",
    titleTranslate: "Español (Latinoamérica y el Caribe)",
  },
  { key: "et", title: "Estonian", titleTranslate: "Eesti" },
  { key: "fa-IR", title: "Persian", titleTranslate: "فارسی" },
  { key: "fi", title: "Finnish", titleTranslate: "Suomi" },
  { key: "fil", title: "Filipino", titleTranslate: "Filipino" },
  { key: "fr", title: "French", titleTranslate: "Français" },
  { key: "gu", title: "Gujarati", titleTranslate: "ગુજરાતી" },
  { key: "he", title: "Hebrew", titleTranslate: "עברית" },
  { key: "hi", title: "Hindi", titleTranslate: "हिन्दी" },
  { key: "hr", title: "Croatian", titleTranslate: "Hrvatski" },
  { key: "hu", title: "Hungarian", titleTranslate: "Magyar" },
  { key: "id", title: "Indonesian", titleTranslate: "Bahasa Indonesia" },
  { key: "it", title: "Italian", titleTranslate: "Italiano" },
  { key: "ja", title: "Japanese", titleTranslate: "日本語" },
  { key: "kn", title: "Kannada", titleTranslate: "ಕನ್ನಡ" },
  { key: "ko", title: "Korean", titleTranslate: "한국어" },
  { key: "lt", title: "Lithuanian", titleTranslate: "Lietuvių" },
  { key: "lv", title: "Latvian", titleTranslate: "Latviešu" },
  { key: "ml", title: "Malayalam", titleTranslate: "മലയാളം" },
  { key: "mr", title: "Marathi", titleTranslate: "मराठी" },
  { key: "ms", title: "Malay", titleTranslate: "Bahasa Melayu" },
  { key: "nl", title: "Dutch", titleTranslate: "Nederlands" },
  { key: "no", title: "Norwegian", titleTranslate: "Norsk" },
  { key: "pl", title: "Polish", titleTranslate: "Polski" },
  {
    key: "pt-BR",
    title: "Portuguese (Brazil)",
    titleTranslate: "Português (Brasil)",
  },
  {
    key: "pt-PT",
    title: "Portuguese (Portugal)",
    titleTranslate: "Português (Portugal)",
  },
  { key: "ro", title: "Romanian", titleTranslate: "Română" },
  { key: "ru", title: "Russian", titleTranslate: "Русский" },
  { key: "sk", title: "Slovak", titleTranslate: "Slovenčina" },
  { key: "sl", title: "Slovenian", titleTranslate: "Slovenščina" },
  { key: "sr", title: "Serbian", titleTranslate: "Српски" },
  { key: "sv", title: "Swedish", titleTranslate: "Svenska" },
  { key: "sw", title: "Swahili", titleTranslate: "Kiswahili" },
  { key: "ta", title: "Tamil", titleTranslate: "தமிழ்" },
  { key: "te", title: "Telugu", titleTranslate: "తెలుగు" },
  { key: "th", title: "Thai", titleTranslate: "ไทย" },
  { key: "tr", title: "Turkish", titleTranslate: "Türkçe" },
  { key: "uk", title: "Ukrainian", titleTranslate: "Українська" },
  { key: "vi", title: "Vietnamese", titleTranslate: "Tiếng Việt" },
  { key: "zh-CN", title: "Chinese (China)", titleTranslate: "中文（中国）" },
  { key: "zh-TW", title: "Chinese (Taiwan)", titleTranslate: "中文（台灣）" },
];
